export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LIST_ALL_EMPLOYEES_SUCCESS = 'LIST_ALL_EMPLOYEES_SUCCESS';
export const DELETE_ONE_EMPLOYEE_SUCCESS = 'DELETE_ONE_EMPLOYEE_SUCCESS';
export const EDIT_ONE_EMPLOYEE_SUCCESS = 'EDIT_ONE_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';